# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# copy from pyscf project

sudo: required
language: python
os: 
  - linux
  - osx

python:
  - 3.5
  - 3.6

install:
  - sudo python -m pip install -r requirements.txt
  - make README.rst

before_script:
  - export VASPPOT=$TRAVIS_BUILD_DIR/vasppot_sample

script:
  - make build
  - make sudoinstall
  - make test


